---
name: relint-trackerbot

releases:
- name: relint-trackerbot
  url: file://.
  version: create
- name: bpm
  version: "0.2.0"
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=0.2.0
  sha1: f2bd126b17b3591160f501d88d79ccf0aba1ae54

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: main
  azs: [z1]
  instances: 1
  jobs:
  - name: bpm
    release: bpm
  - name: relint-trackerbot
    release: relint-trackerbot
    properties:
      concourse_host: ((concourse_host))
      tracker_api_token: ((tracker_api_token))
      tracker_project_id: ((tracker_project_id))
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks:
  - name: default


